# Generated by Django 3.1.6 on 2021-03-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='is_choosen',
            field=models.BooleanField(default=True),
        ),
    ]
