# Generated by Django 3.1.6 on 2021-03-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userpreference_is_choosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ram', models.TextField()),
                ('cpu', models.TextField()),
                ('camera', models.TextField()),
                ('memory', models.TextField()),
                ('battery', models.TextField()),
            ],
        ),
    ]
