# Generated by Django 3.1.6 on 2021-03-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210326_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Smartphone',
        ),
    ]
