# Generated by Django 3.1.6 on 2021-03-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('ram', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('camera', models.CharField(max_length=255)),
                ('memory', models.CharField(max_length=255)),
                ('battery', models.CharField(max_length=255)),
                ('url', models.CharField(default='unknown', max_length=255)),
                ('img_url', models.CharField(default='unknown', max_length=255)),
            ],
        ),
    ]
