# Generated by Django 3.1.6 on 2021-03-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_smartphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
