# Generated by Django 3.1.6 on 2021-03-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210326_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='camera',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='main_cam',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='selfie_cam',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
