# Generated by Django 3.1.6 on 2021-03-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210326_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
