# Generated by Django 3.1.6 on 2021-03-30 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210326_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=255)),
                ('rank', models.IntegerField()),
                ('price', models.IntegerField()),
                ('url', models.TextField()),
                ('smartphone_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.smartphone')),
            ],
        ),
    ]
