# Generated by Django 3.1.6 on 2021-03-31 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210331_1003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
