# Generated by Django 3.1.6 on 2021-03-31 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210331_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url_product',
            new_name='url',
        ),
    ]
