# Generated by Django 3.1.6 on 2021-03-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20210331_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='url',
            new_name='product_url',
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='battery',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='cpu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_cam',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='selfie_cam',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='storage',
            field=models.FloatField(),
        ),
    ]
