# Generated by Django 3.1.6 on 2021-04-07 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_recomendation_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendation',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
