# Generated by Django 3.1.6 on 2021-04-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210407_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='recomendation',
            name='smartphone_cart',
        ),
        migrations.DeleteModel(
            name='ProductRecommendation',
        ),
        migrations.DeleteModel(
            name='Recomendation',
        ),
    ]
