# Generated by Django 3.1.6 on 2021-04-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210408_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
