# Generated by Django 3.1.6 on 2021-04-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_productrecommendation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrecommendation',
            name='smartphone_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cart'),
        ),
    ]
