# Generated by Django 3.1.6 on 2021-04-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210408_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productrecommendation',
            old_name='smartphone_cart',
            new_name='cart',
        ),
    ]
