# Generated by Django 3.1.6 on 2021-04-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210408_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='relevance',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
