# Generated by Django 3.1.6 on 2021-04-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_productrecommendation_relevance'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrecommendation',
            name='score',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
