# Generated by Django 3.1.6 on 2021-04-09 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_productrecommendation_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrecommendation',
            name='score',
        ),
    ]
